import numpy as np

LED_METER_DENSITY = 144.0/1000.0 #leds/m

# pitch
MIN_PIXEL_PITCH = 1
MAX_PIXEL_PITCH  = 14
STEP_PIXEL_PITCH = 1
DEFAULT_PIXEL_PITCH = 7

# mass
MIN_STRIP_MASS = 22
MAX_STRIP_MASS = 220
STEP_STRIP_MASS = 1
DEFAULT_STRIP_MASS = 22

# angular speed 
MIN_ANGULAR_SPEED = 150
MAX_ANGULAR_SPEED = 330 
STEP_ANGULAR_SPEED = 1
DEFAULT_ANGULAR_SPEED = 225

# hole width
MIN_HOLE_RADIUS = 189/2.0 # 205.782cm
MAX_HOLE_RADIUS = MIN_HOLE_RADIUS * 3.0 #cm
STEP_HOLE_RADIUS = 1
DEFAULT_HOLE_RADIUS = 189/2.0

MIN_VERTICAL_RESOLUTION = 31 # 220
MAX_VERTICAL_RESOLUTION = MIN_VERTICAL_RESOLUTION + 77
 

# strip length
MIN_TOP_ROPE_LENGTH_OFFSET = 0
MAX_TOP_ROPE_LENGTH_OFFSET = 30 * DEFAULT_PIXEL_PITCH
STEP_TOP_ROPE_LENGTH_OFFSET = DEFAULT_PIXEL_PITCH
DEFAULT_TOP_ROPE_LENGTH_OFFSET = 3 * DEFAULT_PIXEL_PITCH


# strip length
MIN_ROPE_LENGTH = MIN_VERTICAL_RESOLUTION * DEFAULT_PIXEL_PITCH
MAX_ROPE_LENGTH = MAX_VERTICAL_RESOLUTION * DEFAULT_PIXEL_PITCH
STEP_ROPE_LENGTH = DEFAULT_PIXEL_PITCH
DEFAULT_ROPE_LENGTH = MIN_ROPE_LENGTH

# strip height
MIN_POLE_HEIGHT = 200
MAX_POLE_HEIGHT = MIN_POLE_HEIGHT + 43 * DEFAULT_PIXEL_PITCH
STEP_POLE_HEIGHT = DEFAULT_PIXEL_PITCH
DEFAULT_POLE_HEIGHT = MIN_POLE_HEIGHT

speed_factors = np.array([150, 180, 210, 240, 270, 300, 330])
height_factors = np.array([10, 15, 20, 25])
height_values = np.array([200, 300, 400, 500]) # maybe 198.5?
length_factors = np.array([10, 15, 20, 25, 30, 35])
init_length_pixels = 31.0
length_pixels = np.array([0, 15, 31, 46, 62, 77]).astype(np.float64)
length_pixels += init_length_pixels
length_values = length_pixels * 7
strip_factors = np.array([1, 2, 3, 4])